// The single canonical verification notice for Tenure Monitor.
//
// One constant, imported by every surface that shows tenure data — portfolio
// header, detail panel, CSV export footer, every alert email, the admin tools.
// A disclaimer that is reworded per screen is a disclaimer nobody trusts, and
// this product touches decisions about mineral rights: the user must always
// be one glance from knowing that MTO, not Exploration Maps, is the registry.
//
// Keep these strings verbatim. If the wording has to change, change it here
// so every surface moves together.

/** The standing notice. Shown on every material Tenure Monitor view. */
export const TENURE_VERIFICATION_NOTICE =
  'Government title records and Exploration Maps monitoring results should be '
  + 'verified in the official Mineral Titles Online registry before a transaction '
  + 'or deadline decision.';

/** Short form for tight spaces (table footers, email footers, tooltips). */
export const TENURE_VERIFICATION_SHORT =
  'Exploration Maps is not the official title registry — verify in MTO.';

/**
 * What an alert is, and is not. Included in every alert email so a reminder is
 * never mistaken for a legal notice from the province.
 */
export const TENURE_ALERT_DISCLAIMER =
  'This reminder is generated by Exploration Maps from public B.C. tenure data. '
  + 'It is not a legal notice, and it does not maintain, renew, or register any '
  + 'title. Government records control.';

/** Why a missing record is not the same thing as a lapsed one. */
export const TENURE_NOT_OBSERVED_NOTICE =
  'This title was not present in the latest successful dataset. Verify its status in MTO.';

/** Shown wherever a field the source did not publish would otherwise be blank. */
export const FIELD_NOT_PUBLISHED = 'Not published in the B.C. source';

/** Attribution required by the Open Government Licence – British Columbia. */
export const BC_DATA_ATTRIBUTION =
  'Contains information licensed under the Open Government Licence – British Columbia.';

/** The official MTO entry point. Public, no account needed to reach it. */
export const MTO_URL = 'https://www.mtonline.gov.bc.ca/mtov/home.do';

/** Province's Mineral Titles branch — background, rules, contact. */
export const MTO_INFO_URL = 'https://www2.gov.bc.ca/gov/content/industry/mineral-exploration-mining/mineral-titles';

/**
 * Where to send a user to verify one specific tenure.
 *
 * MTO's public search is a stateful JSP application with no documented,
 * stable deep-link contract for a single tenure, so we deliberately do NOT
 * fabricate a query-string that may silently break or, worse, land the user on
 * the wrong title. We send them to the registry's front door and tell them the
 * number to type. An honest two-step beats a clever link that rots.
 *
 * @param {string|number} _tenureNumber Kept in the signature so call sites read
 *   naturally and so a real deep link can be adopted later in exactly one place.
 */
export function mtoVerifyUrl(_tenureNumber) {
  return MTO_URL;
}

/** The instruction that accompanies the verify link. */
export function mtoVerifyHint(tenureNumber) {
  return tenureNumber
    ? `Open Mineral Titles Online and search tenure number ${tenureNumber}.`
    : 'Open Mineral Titles Online to verify this record.';
}
